server:
  port: 8001
logging:
  level.root: info


spring:
  datasource:
    username: root
    password: cloudalibaba
    url: jdbc:mysql://zmz121.cn:3306/mmall?useSSL=true&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: zmz121.cn
    port: 6379
    timeout: 1000
    jedis:
      pool:
        max-active: 10
        max-idle: 10
        max-wait: 3
    password: cloudalibaba


  main:
    allow-bean-definition-overriding: true


token:
  secret: nwafu
  # 单位 分钟
  expiration: 30

dubbo:
  registry:
    address: nacos://zmz121.cn:8848?namespace=f678b632-7899-4a2d-acd7-8c7c3394b573
  protocol:
    name: dubbo
    port: 20001



mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml