spring:
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/mmall
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false
  redis:
    host: localhost
    port: 6379
    timeout: 1000
    jedis:
      pool:
        max-active: 10
        max-idle: 10
        max-wait: 3
    password: 123
  profiles:
    active: zmz-dev
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

server:
  port: 8080
logging:
  level.main: debug
#  file: log.txt
